apiVersion: apps/v1
kind: Deployment
metadata:
  name: mannazu-tomcat
  namespace: mannazu
spec:
  replicas: 1
  revisionHistoryLimit: 1  # 보관할 ReplicaSet의 수를 3로 제한
  selector:
    matchLabels:
      app: mannazu-tomcat
  template:
    metadata:
      labels:
        app: mannazu-tomcat
    spec:
      containers:
      - name: mannazu-tomcat
        image: harbor.dorong9.com/mannazo/back-springtomcat:38
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: mannazu-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mannazu-tomcat
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mannazu-tomcat