apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: admin-service
  namespace: mannazu
spec:
  revisionHistoryLimit: 1  # 보관할 ReplicaSet의 수를 3로 제한
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: harbor.dorong9.com/mannazo/admin-service:166
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 125m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1000Mi  
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/app/config/application.properties
      volumes:
      - name: config-volume
        configMap:
          name: admin-service-config
      imagePullSecrets:
      - name: mannazu-regcred
  strategy:
    canary:
      canaryService: admin-service-canary
      stableService: admin-service-stable    
      steps:
      - setWeight: 50
      - pause: {duration: 20m}
      maxSurge: "50%"
      maxUnavailable: 0            
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-stable
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: admin-service
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-canary
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: admin-service