apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: chat-service
  namespace: mannazu
spec:
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: harbor.dorong9.com/mannazo/chat-service:61
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 500m
            memory: 256Mi  
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/app/config/application.properties
      volumes:
      - name: config-volume
        configMap:
          name: chat-service-config
      imagePullSecrets:
      - name: mannazu-regcred
  strategy:
    canary:
      canaryService: chat-service-canary
      stableService: chat-service-stable    
      steps:
      - setWeight: 50
      - pause: {duration: 20m}
      maxSurge: "50%"
      maxUnavailable: 0        
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-stable
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: chat-service
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-canary
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: chat-service