apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mannazu-mongodb
  namespace: mannazu
spec:
  serviceName: mannazu-mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mannazu-mongodb
  template:
    metadata:
      labels:
        app: mannazu-mongodb
    spec:
      initContainers:
        - name: init-mongodb
          image: mongo:4.2.24-bionic
          command:
            - "bash"
            - "-c"
            - |
              sleep 30  # MongoDB가 시작될 때까지 대기
              mongo --host mannazu-mongodb-service:27017 -u root -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin /docker-entrypoint-initdb.d/init-mongodb.js
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      containers:
        - name: mannazu-mongodb
          image: mongo:4.2.24-bionic
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-password
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mannazu-mongodb-pvc
        - name: init-scripts
          configMap:
            name: mongodb-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mannazu-mongodb-service
  namespace: mannazu
spec:
  selector:
    app: mannazu-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
