apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mannazu-redis-pvc
  namespace: mannazu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi   # PV와 동일한 용량을 요청
