apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-service
  namespace: mannazu
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: swagger-service
  template:
    metadata:
      labels:
        app: swagger-service
    spec:
      containers:
      - name: swagger-service
        image: harbor.dorong9.com/mannazo/swagger-service:12
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 125m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1000Mi  
      imagePullSecrets:
      - name: mannazu-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: swagger-service
