apiVersion: apps/v1
kind: Deployment
metadata:
  name: mannazu-nginx
  namespace: mannazu
spec:
  revisionHistoryLimit: 1  # 보관할 ReplicaSet의 수를 3로 제한
  selector:
    matchLabels:
      app: mannazu-nginx
  template:
    metadata:
      labels:
        app: mannazu-nginx
    spec:
      containers:
      - name: mannazo-nginx
        image: harbor.dorong9.com/mannazo/front-react:115
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"   
      imagePullSecrets:
      - name: mannazu-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mannazu-nginx
  namespace: mannazu
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mannazu-nginx