apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mannazu-nginx-hpa
  namespace: mannazu
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: mannazu-nginx
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70